name: flutter_simple_typewriter
description: A simple package to create typewriter effects in hint texts for TextFormField.
version: 0.0.1+1
homepage: https://github.com/musfique113/flutter_simple_typewriter
environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter



